-- Budget structure (Phase 2). RE-AUTHORED Aug 11, 2026 - this file previously created two
-- relational tables (rfp_budget_categories, bid_budget_lines). That draft was never applied
-- (verified: neither table exists live), so replacing it costs nothing.
--
-- Why it was replaced, in full - see docs/p2-reconciliation.md section 3:
--
-- app/api/agency/broadcast-rfp/route.ts writes ONE partner_rfp_inbox row per (scope item x
-- recipient). A broadcast to 6 vendors across 3 scope items is 18 rows. Parenting a budget
-- category on a single inbox_item_id therefore forces the wizard's one set of categories to be
-- copied 18 times, each copy with its own UUIDs. Two vendors bidding the SAME scope item would
-- then hold budget lines pointing at different category rows carrying the same name, and the
-- compare view would have to reconcile by name anyway - defeating the entire point of the
-- relational model, and falsifying the Phase 2 plan's stated premise that "category identity is
-- shared across all bids being compared."
--
-- This codebase already solved that exact problem for business_criteria_required: the config
-- lives inside JSONB that fans out with the rows, and the KEYS inside the blob stay stable and
-- identical across every copy, so identity survives the fan-out for free. Budget categories
-- follow that precedent rather than fighting it.
--
-- Storage map (mirrors business_criteria_required exactly):
--   wizard flow     -> partner_rfp_inbox.master_rfp_json.budget_categories  (no column needed)
--   magic-link flow -> rfp_magic_tokens.budget_categories                   (added below)
--   vendor's numbers-> partner_rfp_responses.budget_lines                   (added below)
--
-- Consequences, all of them simplifications:
--   * No new tables, so no new RLS surface. The Phase 2 plan's open item 3 ("write RLS policies
--     for both new tables before shipping") and its judgment call 2 (guest direct-write vs
--     service-role route) both dissolve - budget data inherits the row-level policies already
--     governing partner_rfp_inbox / rfp_magic_tokens / partner_rfp_responses.
--   * Guest bids need no new access model: app/api/rfp/guest/[token]/route.ts already writes
--     business_criteria_responses on this same row with the service client.
--   * Pre-migration safety uses the 42703 retry guard this repo already runs twice
--     (saveGuestResponseRow, saveResponseRow) rather than a new mechanism.
--
-- Shapes are documented and normalized in lib/budget-categories.ts. Summarized here so this
-- file stands alone:
--
--   budget_categories: [
--     { key: string,            -- stable id, generated once at authoring time, never reused
--       name: string,
--       note: string | null,    -- optional agency guidance shown under the category
--       origin: 'preset:<bundle>:<slug>' | 'custom' | 'paste',
--       is_additional_items: boolean,   -- exactly one true per RFP, enforced app-side
--       sort_order: number }
--   ]
--
--   budget_lines: {
--     currency: string,                 -- snapshot of the bid's currency at submit time
--     categories: [
--       { key: string,                  -- matches budget_categories[].key
--         name_snapshot: string,        -- survives an agency renaming the category later
--         subtotal: number,             -- honest 0 is valid and meaningful (container test)
--         items: [ { description: string, amount: number } ] | []  -- when itemized, subtotal
--       }                                                          -- is SUM(items) and is
--     ]                                                            -- derived, never a second
--   }                                                              -- editable number
--
-- One source per number: when items is non-empty, subtotal is written as the computed sum and
-- the UI renders it read-only. It is stored (not left null) so every reader gets the number
-- without re-summing, but no surface ever lets it be edited independently of its items.

ALTER TABLE rfp_magic_tokens
  ADD COLUMN IF NOT EXISTS budget_categories jsonb NULL;

ALTER TABLE partner_rfp_responses
  ADD COLUMN IF NOT EXISTS budget_lines jsonb NULL;

-- NULL, not '[]'/'{}': "this RFP defines no categories" and "this bid entered no category
-- numbers" must both be distinguishable from "defined, and empty". Every reader treats NULL and
-- an empty array identically today, but a default would destroy the distinction permanently.

-- Verification (run manually after applying; not part of the migration):
--
-- SELECT table_name, column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE (table_name = 'rfp_magic_tokens' AND column_name = 'budget_categories')
--    OR (table_name = 'partner_rfp_responses' AND column_name = 'budget_lines')
-- ORDER BY table_name;
-- -- Expected: 2 rows, both data_type = jsonb, is_nullable = YES, column_default = NULL
--
-- SELECT count(*) FROM rfp_magic_tokens WHERE budget_categories IS NOT NULL;
-- SELECT count(*) FROM partner_rfp_responses WHERE budget_lines IS NOT NULL;
-- -- Expected: 0, 0 (nothing has ever written these columns - they did not exist until now)
--
-- SELECT count(*) FROM partner_rfp_inbox WHERE master_rfp_json ? 'budget_categories';
-- -- Expected: 0 (the wizard flow's storage location, also never written before Phase 2 code)
